INSERT INTO cards (card_name, affiliation, rarity, mana_cost, max_level, description, icon_url) VALUES
('Fire Imp', 1, 'common', 2, 5, 'A small fire creature', 'https://example.com/fire_imp.png'),
('Water Sprite', 1, 'common', 2, 5, 'A playful water elemental', 'https://example.com/water_sprite.png'),
('Earth Golem', 1, 'common', 3, 5, 'A sturdy earth golem', 'https://example.com/earth_golem.png'),
('Wind Walker', 1, 'common', 2, 5, 'A swift wind unit', 'https://example.com/wind_walker.png'),
('Shadow Cat', 1, 'common', 1, 5, 'A sneaky shadow cat', 'https://example.com/shadow_cat.png'),
('Iron Shield', 1, 'common', 3, 5, 'A defensive shield bearer', 'https://example.com/iron_shield.png'),
('Frost Archer', 1, 'common', 2, 5, 'A cold precision shooter', 'https://example.com/frost_archer.png'),
('Stone Sentry', 1, 'common', 3, 5, 'A vigilant stone guardian', 'https://example.com/stone_sentry.png'),
('Vine Creeper', 1, 'common', 1, 5, 'A tangling vine creature', 'https://example.com/vine_creeper.png'),
('Spark Wisp', 1, 'common', 1, 5, 'A tiny spark of lightning', 'https://example.com/spark_wisp.png'),
('Sand Beetle', 1, 'common', 2, 5, 'A resilient desert insect', 'https://example.com/sand_beetle.png'),
('Cloud Puff', 1, 'common', 1, 5, 'A fluffy cloud creature', 'https://example.com/cloud_puff.png'),
('Flame Knight', 1, 'rare', 4, 8, 'A powerful fire knight', 'https://example.com/flame_knight.png'),
('Ice Mage', 1, 'rare', 4, 8, 'A frost-wielding mage', 'https://example.com/ice_mage.png'),
('Storm Rider', 1, 'rare', 5, 8, 'A lightning cavalry unit', 'https://example.com/storm_rider.png'),
('Dark Rogue', 1, 'rare', 3, 8, 'A shadow assassin', 'https://example.com/dark_rogue.png'),
('Holy Cleric', 1, 'rare', 4, 8, 'A healer of the light', 'https://example.com/holy_cleric.png'),
('Thunder Drake', 1, 'epic', 6, 10, 'A lightning-breathing dragon', 'https://example.com/thunder_drake.png'),
('Crystal Golem', 1, 'epic', 7, 10, 'A massive crystal construct', 'https://example.com/crystal_golem.png'),
('Void Walker', 1, 'epic', 6, 10, 'A being from the void', 'https://example.com/void_walker.png'),
('Phoenix Lord', 1, 'legendary', 8, 10, 'A legendary phoenix of rebirth', 'https://example.com/phoenix_lord.png'),
('Dragon King', 1, 'legendary', 9, 10, 'The king of all dragons', 'https://example.com/dragon_king.png');
