// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: auth.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const banUser = `-- name: BanUser :exec
UPDATE users SET is_banned = TRUE, banned_at = NOW(), ban_reason = ? WHERE id = ?
`

type BanUserParams struct {
	BanReason *string `json:"ban_reason"`
	ID        int64   `json:"id"`
}

func (q *Queries) BanUser(ctx context.Context, arg BanUserParams) error {
	_, err := q.db.ExecContext(ctx, banUser, arg.BanReason, arg.ID)
	return err
}

const createSession = `-- name: CreateSession :exec
INSERT INTO user_sessions (user_id, token, ip_address, user_agent, expires_at) VALUES (?, ?, ?, ?, ?)
`

type CreateSessionParams struct {
	UserID    int64     `json:"user_id"`
	Token     string    `json:"token"`
	IpAddress *string   `json:"ip_address"`
	UserAgent *string   `json:"user_agent"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession,
		arg.UserID,
		arg.Token,
		arg.IpAddress,
		arg.UserAgent,
		arg.ExpiresAt,
	)
	return err
}

const createUserAuth = `-- name: CreateUserAuth :execresult
INSERT INTO users (username, password_hash) VALUES (?, ?)
`

type CreateUserAuthParams struct {
	Username     string `json:"username"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) CreateUserAuth(ctx context.Context, arg CreateUserAuthParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createUserAuth, arg.Username, arg.PasswordHash)
}

const getActiveTokensByUser = `-- name: GetActiveTokensByUser :many
SELECT token FROM user_sessions WHERE user_id = ? AND revoked_at IS NULL AND expires_at > NOW()
`

func (q *Queries) GetActiveTokensByUser(ctx context.Context, userID int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getActiveTokensByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var token string
		if err := rows.Scan(&token); err != nil {
			return nil, err
		}
		items = append(items, token)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByUsernameAuth = `-- name: GetUserByUsernameAuth :one
SELECT id, username, password_hash, is_banned, ban_reason FROM users WHERE username = ?
`

type GetUserByUsernameAuthRow struct {
	ID           int64   `json:"id"`
	Username     string  `json:"username"`
	PasswordHash string  `json:"password_hash"`
	IsBanned     bool    `json:"is_banned"`
	BanReason    *string `json:"ban_reason"`
}

func (q *Queries) GetUserByUsernameAuth(ctx context.Context, username string) (GetUserByUsernameAuthRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsernameAuth, username)
	var i GetUserByUsernameAuthRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.IsBanned,
		&i.BanReason,
	)
	return i, err
}

const revokeAllUserSessions = `-- name: RevokeAllUserSessions :exec
UPDATE user_sessions SET revoked_at = NOW() WHERE user_id = ? AND revoked_at IS NULL
`

func (q *Queries) RevokeAllUserSessions(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, revokeAllUserSessions, userID)
	return err
}

const revokeSessionByToken = `-- name: RevokeSessionByToken :exec
UPDATE user_sessions SET revoked_at = NOW() WHERE token = ? AND revoked_at IS NULL
`

func (q *Queries) RevokeSessionByToken(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, revokeSessionByToken, token)
	return err
}

const unbanUser = `-- name: UnbanUser :exec
UPDATE users SET is_banned = FALSE, banned_at = NULL, ban_reason = NULL WHERE id = ?
`

func (q *Queries) UnbanUser(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, unbanUser, id)
	return err
}

const validateSession = `-- name: ValidateSession :one
SELECT s.user_id, u.username, s.expires_at, u.is_banned
FROM user_sessions s
JOIN users u ON s.user_id = u.id
WHERE s.token = ? AND s.revoked_at IS NULL AND s.expires_at > NOW()
`

type ValidateSessionRow struct {
	UserID    int64     `json:"user_id"`
	Username  string    `json:"username"`
	ExpiresAt time.Time `json:"expires_at"`
	IsBanned  bool      `json:"is_banned"`
}

func (q *Queries) ValidateSession(ctx context.Context, token string) (ValidateSessionRow, error) {
	row := q.db.QueryRowContext(ctx, validateSession, token)
	var i ValidateSessionRow
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.ExpiresAt,
		&i.IsBanned,
	)
	return i, err
}
