// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: deck.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"
)

const createDeck = `-- name: CreateDeck :execresult
INSERT INTO decks (player_id, name) VALUES (?, ?)
`

type CreateDeckParams struct {
	PlayerID int64  `json:"player_id"`
	Name     string `json:"name"`
}

func (q *Queries) CreateDeck(ctx context.Context, arg CreateDeckParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createDeck, arg.PlayerID, arg.Name)
}

const createPack = `-- name: CreatePack :execresult
INSERT INTO card_packs (player_id, pack_type) VALUES (?, ?)
`

type CreatePackParams struct {
	PlayerID int64  `json:"player_id"`
	PackType string `json:"pack_type"`
}

func (q *Queries) CreatePack(ctx context.Context, arg CreatePackParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createPack, arg.PlayerID, arg.PackType)
}

const deleteDeck = `-- name: DeleteDeck :execresult
DELETE FROM decks WHERE deck_id = ? AND player_id = ?
`

type DeleteDeckParams struct {
	DeckID   int32 `json:"deck_id"`
	PlayerID int64 `json:"player_id"`
}

func (q *Queries) DeleteDeck(ctx context.Context, arg DeleteDeckParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteDeck, arg.DeckID, arg.PlayerID)
}

const deleteDeckCards = `-- name: DeleteDeckCards :exec
DELETE FROM deck_cards WHERE deck_id = ?
`

func (q *Queries) DeleteDeckCards(ctx context.Context, deckID int32) error {
	_, err := q.db.ExecContext(ctx, deleteDeckCards, deckID)
	return err
}

const getAbilitiesForDeck = `-- name: GetAbilitiesForDeck :many
SELECT ca.card_id, ca.trigger_type, ca.effect_type, ca.params
FROM card_abilities ca
WHERE ca.card_id IN (
    SELECT dc.card_id FROM deck_cards dc WHERE dc.deck_id = ?
)
ORDER BY ca.card_id, ca.ability_id
`

type GetAbilitiesForDeckRow struct {
	CardID      int32           `json:"card_id"`
	TriggerType string          `json:"trigger_type"`
	EffectType  string          `json:"effect_type"`
	Params      json.RawMessage `json:"params"`
}

func (q *Queries) GetAbilitiesForDeck(ctx context.Context, deckID int32) ([]GetAbilitiesForDeckRow, error) {
	rows, err := q.db.QueryContext(ctx, getAbilitiesForDeck, deckID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAbilitiesForDeckRow{}
	for rows.Next() {
		var i GetAbilitiesForDeckRow
		if err := rows.Scan(
			&i.CardID,
			&i.TriggerType,
			&i.EffectType,
			&i.Params,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getActiveDeck = `-- name: GetActiveDeck :one
SELECT active_deck_id FROM users WHERE id = ?
`

func (q *Queries) GetActiveDeck(ctx context.Context, id int64) (*int32, error) {
	row := q.db.QueryRowContext(ctx, getActiveDeck, id)
	var active_deck_id *int32
	err := row.Scan(&active_deck_id)
	return active_deck_id, err
}

const getAllCardAbilities = `-- name: GetAllCardAbilities :many
SELECT card_id, trigger_type, effect_type, params
FROM card_abilities ORDER BY card_id, ability_id
`

type GetAllCardAbilitiesRow struct {
	CardID      int32           `json:"card_id"`
	TriggerType string          `json:"trigger_type"`
	EffectType  string          `json:"effect_type"`
	Params      json.RawMessage `json:"params"`
}

func (q *Queries) GetAllCardAbilities(ctx context.Context) ([]GetAllCardAbilitiesRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllCardAbilities)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAllCardAbilitiesRow{}
	for rows.Next() {
		var i GetAllCardAbilitiesRow
		if err := rows.Scan(
			&i.CardID,
			&i.TriggerType,
			&i.EffectType,
			&i.Params,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllCardDefinitions = `-- name: GetAllCardDefinitions :many
SELECT c.card_id, c.card_name, c.affiliation, c.rarity, c.mana_cost,
       COALESCE(cs.power, 0) AS attack, COALESCE(cs.hp, 0) AS hp
FROM cards c
LEFT JOIN card_stats cs ON cs.card_id = c.card_id AND cs.level = 1
ORDER BY c.card_id
`

type GetAllCardDefinitionsRow struct {
	CardID      int32  `json:"card_id"`
	CardName    string `json:"card_name"`
	Affiliation int32  `json:"affiliation"`
	Rarity      string `json:"rarity"`
	ManaCost    int32  `json:"mana_cost"`
	Attack      int32  `json:"attack"`
	Hp          int32  `json:"hp"`
}

func (q *Queries) GetAllCardDefinitions(ctx context.Context) ([]GetAllCardDefinitionsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllCardDefinitions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAllCardDefinitionsRow{}
	for rows.Next() {
		var i GetAllCardDefinitionsRow
		if err := rows.Scan(
			&i.CardID,
			&i.CardName,
			&i.Affiliation,
			&i.Rarity,
			&i.ManaCost,
			&i.Attack,
			&i.Hp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllCards = `-- name: GetAllCards :many
SELECT card_id, card_name, affiliation, rarity, mana_cost, description, icon_url
FROM cards ORDER BY card_id ASC
`

func (q *Queries) GetAllCards(ctx context.Context) ([]Card, error) {
	rows, err := q.db.QueryContext(ctx, getAllCards)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Card{}
	for rows.Next() {
		var i Card
		if err := rows.Scan(
			&i.CardID,
			&i.CardName,
			&i.Affiliation,
			&i.Rarity,
			&i.ManaCost,
			&i.Description,
			&i.IconUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllCardsByAffiliation = `-- name: GetAllCardsByAffiliation :many
SELECT card_id, card_name, affiliation, rarity, mana_cost, description, icon_url
FROM cards WHERE affiliation = ? ORDER BY card_id ASC
`

func (q *Queries) GetAllCardsByAffiliation(ctx context.Context, affiliation int32) ([]Card, error) {
	rows, err := q.db.QueryContext(ctx, getAllCardsByAffiliation, affiliation)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Card{}
	for rows.Next() {
		var i Card
		if err := rows.Scan(
			&i.CardID,
			&i.CardName,
			&i.Affiliation,
			&i.Rarity,
			&i.ManaCost,
			&i.Description,
			&i.IconUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllCardsByRarity = `-- name: GetAllCardsByRarity :many
SELECT card_id, card_name, affiliation, rarity, mana_cost, description, icon_url
FROM cards WHERE rarity = ? ORDER BY card_id ASC
`

func (q *Queries) GetAllCardsByRarity(ctx context.Context, rarity string) ([]Card, error) {
	rows, err := q.db.QueryContext(ctx, getAllCardsByRarity, rarity)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Card{}
	for rows.Next() {
		var i Card
		if err := rows.Scan(
			&i.CardID,
			&i.CardName,
			&i.Affiliation,
			&i.Rarity,
			&i.ManaCost,
			&i.Description,
			&i.IconUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllCardsByRarityAndAffiliation = `-- name: GetAllCardsByRarityAndAffiliation :many
SELECT card_id, card_name, affiliation, rarity, mana_cost, description, icon_url
FROM cards WHERE rarity = ? AND affiliation = ? ORDER BY card_id ASC
`

type GetAllCardsByRarityAndAffiliationParams struct {
	Rarity      string `json:"rarity"`
	Affiliation int32  `json:"affiliation"`
}

func (q *Queries) GetAllCardsByRarityAndAffiliation(ctx context.Context, arg GetAllCardsByRarityAndAffiliationParams) ([]Card, error) {
	rows, err := q.db.QueryContext(ctx, getAllCardsByRarityAndAffiliation, arg.Rarity, arg.Affiliation)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Card{}
	for rows.Next() {
		var i Card
		if err := rows.Scan(
			&i.CardID,
			&i.CardName,
			&i.Affiliation,
			&i.Rarity,
			&i.ManaCost,
			&i.Description,
			&i.IconUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDeckByIDAndPlayer = `-- name: GetDeckByIDAndPlayer :one
SELECT deck_id, name, created_at FROM decks WHERE deck_id = ? AND player_id = ?
`

type GetDeckByIDAndPlayerParams struct {
	DeckID   int32 `json:"deck_id"`
	PlayerID int64 `json:"player_id"`
}

type GetDeckByIDAndPlayerRow struct {
	DeckID    int32     `json:"deck_id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) GetDeckByIDAndPlayer(ctx context.Context, arg GetDeckByIDAndPlayerParams) (GetDeckByIDAndPlayerRow, error) {
	row := q.db.QueryRowContext(ctx, getDeckByIDAndPlayer, arg.DeckID, arg.PlayerID)
	var i GetDeckByIDAndPlayerRow
	err := row.Scan(&i.DeckID, &i.Name, &i.CreatedAt)
	return i, err
}

const getDeckCards = `-- name: GetDeckCards :many
SELECT card_id, position FROM deck_cards WHERE deck_id = ? ORDER BY position
`

type GetDeckCardsRow struct {
	CardID   int32 `json:"card_id"`
	Position int32 `json:"position"`
}

func (q *Queries) GetDeckCards(ctx context.Context, deckID int32) ([]GetDeckCardsRow, error) {
	rows, err := q.db.QueryContext(ctx, getDeckCards, deckID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetDeckCardsRow{}
	for rows.Next() {
		var i GetDeckCardsRow
		if err := rows.Scan(&i.CardID, &i.Position); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDeckCardsWithDetails = `-- name: GetDeckCardsWithDetails :many
SELECT dc.position, c.card_id, c.card_name, c.affiliation, c.rarity, c.mana_cost,
       COALESCE(cs.power, 0) AS attack, COALESCE(cs.hp, 0) AS hp
FROM deck_cards dc
JOIN cards c ON dc.card_id = c.card_id
LEFT JOIN card_stats cs ON cs.card_id = c.card_id AND cs.level = 1
WHERE dc.deck_id = ?
ORDER BY dc.position
`

type GetDeckCardsWithDetailsRow struct {
	Position    int32  `json:"position"`
	CardID      int32  `json:"card_id"`
	CardName    string `json:"card_name"`
	Affiliation int32  `json:"affiliation"`
	Rarity      string `json:"rarity"`
	ManaCost    int32  `json:"mana_cost"`
	Attack      int32  `json:"attack"`
	Hp          int32  `json:"hp"`
}

func (q *Queries) GetDeckCardsWithDetails(ctx context.Context, deckID int32) ([]GetDeckCardsWithDetailsRow, error) {
	rows, err := q.db.QueryContext(ctx, getDeckCardsWithDetails, deckID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetDeckCardsWithDetailsRow{}
	for rows.Next() {
		var i GetDeckCardsWithDetailsRow
		if err := rows.Scan(
			&i.Position,
			&i.CardID,
			&i.CardName,
			&i.Affiliation,
			&i.Rarity,
			&i.ManaCost,
			&i.Attack,
			&i.Hp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPackByIDAndPlayer = `-- name: GetPackByIDAndPlayer :one
SELECT pack_type, is_opened FROM card_packs WHERE pack_id = ? AND player_id = ?
`

type GetPackByIDAndPlayerParams struct {
	PackID   int32 `json:"pack_id"`
	PlayerID int64 `json:"player_id"`
}

type GetPackByIDAndPlayerRow struct {
	PackType string `json:"pack_type"`
	IsOpened bool   `json:"is_opened"`
}

func (q *Queries) GetPackByIDAndPlayer(ctx context.Context, arg GetPackByIDAndPlayerParams) (GetPackByIDAndPlayerRow, error) {
	row := q.db.QueryRowContext(ctx, getPackByIDAndPlayer, arg.PackID, arg.PlayerID)
	var i GetPackByIDAndPlayerRow
	err := row.Scan(&i.PackType, &i.IsOpened)
	return i, err
}

const getPlayerCardOwnership = `-- name: GetPlayerCardOwnership :many
SELECT card_id, quantity FROM player_cards WHERE player_id = ?
`

type GetPlayerCardOwnershipRow struct {
	CardID   int32 `json:"card_id"`
	Quantity int32 `json:"quantity"`
}

func (q *Queries) GetPlayerCardOwnership(ctx context.Context, playerID int64) ([]GetPlayerCardOwnershipRow, error) {
	rows, err := q.db.QueryContext(ctx, getPlayerCardOwnership, playerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPlayerCardOwnershipRow{}
	for rows.Next() {
		var i GetPlayerCardOwnershipRow
		if err := rows.Scan(&i.CardID, &i.Quantity); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlayerCards = `-- name: GetPlayerCards :many
SELECT c.card_id, c.card_name, c.affiliation, c.rarity, c.mana_cost,
       c.description, c.icon_url, pc.level, pc.quantity
FROM player_cards pc
JOIN cards c ON pc.card_id = c.card_id
WHERE pc.player_id = ?
ORDER BY c.rarity DESC, c.card_id ASC
`

type GetPlayerCardsRow struct {
	CardID      int32  `json:"card_id"`
	CardName    string `json:"card_name"`
	Affiliation int32  `json:"affiliation"`
	Rarity      string `json:"rarity"`
	ManaCost    int32  `json:"mana_cost"`
	Description string `json:"description"`
	IconUrl     string `json:"icon_url"`
	Level       int32  `json:"level"`
	Quantity    int32  `json:"quantity"`
}

func (q *Queries) GetPlayerCards(ctx context.Context, playerID int64) ([]GetPlayerCardsRow, error) {
	rows, err := q.db.QueryContext(ctx, getPlayerCards, playerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPlayerCardsRow{}
	for rows.Next() {
		var i GetPlayerCardsRow
		if err := rows.Scan(
			&i.CardID,
			&i.CardName,
			&i.Affiliation,
			&i.Rarity,
			&i.ManaCost,
			&i.Description,
			&i.IconUrl,
			&i.Level,
			&i.Quantity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlayerCardsNotInDeck = `-- name: GetPlayerCardsNotInDeck :many
SELECT c.card_id, c.card_name, c.affiliation, c.rarity, c.mana_cost,
       c.description, c.icon_url, pc.level,
       pc.quantity - COALESCE(in_deck.cnt, 0) AS quantity
FROM player_cards pc
JOIN cards c ON pc.card_id = c.card_id
LEFT JOIN (
    SELECT card_id, COUNT(*) AS cnt
    FROM deck_cards
    WHERE deck_id = ?
    GROUP BY card_id
) in_deck ON in_deck.card_id = pc.card_id
WHERE pc.player_id = ?
  AND pc.quantity > COALESCE(in_deck.cnt, 0)
ORDER BY c.rarity DESC, c.card_id ASC
`

type GetPlayerCardsNotInDeckParams struct {
	DeckID   int32 `json:"deck_id"`
	PlayerID int64 `json:"player_id"`
}

type GetPlayerCardsNotInDeckRow struct {
	CardID      int32  `json:"card_id"`
	CardName    string `json:"card_name"`
	Affiliation int32  `json:"affiliation"`
	Rarity      string `json:"rarity"`
	ManaCost    int32  `json:"mana_cost"`
	Description string `json:"description"`
	IconUrl     string `json:"icon_url"`
	Level       int32  `json:"level"`
	Quantity    int32  `json:"quantity"`
}

func (q *Queries) GetPlayerCardsNotInDeck(ctx context.Context, arg GetPlayerCardsNotInDeckParams) ([]GetPlayerCardsNotInDeckRow, error) {
	rows, err := q.db.QueryContext(ctx, getPlayerCardsNotInDeck, arg.DeckID, arg.PlayerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPlayerCardsNotInDeckRow{}
	for rows.Next() {
		var i GetPlayerCardsNotInDeckRow
		if err := rows.Scan(
			&i.CardID,
			&i.CardName,
			&i.Affiliation,
			&i.Rarity,
			&i.ManaCost,
			&i.Description,
			&i.IconUrl,
			&i.Level,
			&i.Quantity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlayerDeckList = `-- name: GetPlayerDeckList :many
SELECT deck_id, name, created_at FROM decks WHERE player_id = ? ORDER BY deck_id ASC
`

type GetPlayerDeckListRow struct {
	DeckID    int32     `json:"deck_id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) GetPlayerDeckList(ctx context.Context, playerID int64) ([]GetPlayerDeckListRow, error) {
	rows, err := q.db.QueryContext(ctx, getPlayerDeckList, playerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPlayerDeckListRow{}
	for rows.Next() {
		var i GetPlayerDeckListRow
		if err := rows.Scan(&i.DeckID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlayerPacks = `-- name: GetPlayerPacks :many
SELECT pack_id, pack_type, is_opened, created_at FROM card_packs
WHERE player_id = ? ORDER BY created_at DESC
`

type GetPlayerPacksRow struct {
	PackID    int32     `json:"pack_id"`
	PackType  string    `json:"pack_type"`
	IsOpened  bool      `json:"is_opened"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) GetPlayerPacks(ctx context.Context, playerID int64) ([]GetPlayerPacksRow, error) {
	rows, err := q.db.QueryContext(ctx, getPlayerPacks, playerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPlayerPacksRow{}
	for rows.Next() {
		var i GetPlayerPacksRow
		if err := rows.Scan(
			&i.PackID,
			&i.PackType,
			&i.IsOpened,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRandomCardsByRarity = `-- name: GetRandomCardsByRarity :many
SELECT card_id, card_name, rarity FROM cards WHERE rarity = ? ORDER BY RAND() LIMIT ?
`

type GetRandomCardsByRarityParams struct {
	Rarity string `json:"rarity"`
	Limit  int32  `json:"limit"`
}

type GetRandomCardsByRarityRow struct {
	CardID   int32  `json:"card_id"`
	CardName string `json:"card_name"`
	Rarity   string `json:"rarity"`
}

func (q *Queries) GetRandomCardsByRarity(ctx context.Context, arg GetRandomCardsByRarityParams) ([]GetRandomCardsByRarityRow, error) {
	rows, err := q.db.QueryContext(ctx, getRandomCardsByRarity, arg.Rarity, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRandomCardsByRarityRow{}
	for rows.Next() {
		var i GetRandomCardsByRarityRow
		if err := rows.Scan(&i.CardID, &i.CardName, &i.Rarity); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertDeckCard = `-- name: InsertDeckCard :exec
INSERT INTO deck_cards (deck_id, card_id, position) VALUES (?, ?, ?)
`

type InsertDeckCardParams struct {
	DeckID   int32 `json:"deck_id"`
	CardID   int32 `json:"card_id"`
	Position int32 `json:"position"`
}

func (q *Queries) InsertDeckCard(ctx context.Context, arg InsertDeckCardParams) error {
	_, err := q.db.ExecContext(ctx, insertDeckCard, arg.DeckID, arg.CardID, arg.Position)
	return err
}

const openPack = `-- name: OpenPack :exec
UPDATE card_packs SET is_opened = TRUE, opened_at = NOW() WHERE pack_id = ?
`

func (q *Queries) OpenPack(ctx context.Context, packID int32) error {
	_, err := q.db.ExecContext(ctx, openPack, packID)
	return err
}

const setActiveDeck = `-- name: SetActiveDeck :exec
UPDATE users SET active_deck_id = ? WHERE id = ?
`

type SetActiveDeckParams struct {
	ActiveDeckID *int32 `json:"active_deck_id"`
	ID           int64  `json:"id"`
}

func (q *Queries) SetActiveDeck(ctx context.Context, arg SetActiveDeckParams) error {
	_, err := q.db.ExecContext(ctx, setActiveDeck, arg.ActiveDeckID, arg.ID)
	return err
}

const setPlayerCardQuantity = `-- name: SetPlayerCardQuantity :exec
INSERT INTO player_cards (player_id, card_id, level, quantity) VALUES (?, ?, 1, ?)
ON DUPLICATE KEY UPDATE quantity = VALUES(quantity)
`

type SetPlayerCardQuantityParams struct {
	PlayerID int64 `json:"player_id"`
	CardID   int32 `json:"card_id"`
	Quantity int32 `json:"quantity"`
}

func (q *Queries) SetPlayerCardQuantity(ctx context.Context, arg SetPlayerCardQuantityParams) error {
	_, err := q.db.ExecContext(ctx, setPlayerCardQuantity, arg.PlayerID, arg.CardID, arg.Quantity)
	return err
}

const updateDeck = `-- name: UpdateDeck :execresult
UPDATE decks SET name = ? WHERE deck_id = ? AND player_id = ?
`

type UpdateDeckParams struct {
	Name     string `json:"name"`
	DeckID   int32  `json:"deck_id"`
	PlayerID int64  `json:"player_id"`
}

func (q *Queries) UpdateDeck(ctx context.Context, arg UpdateDeckParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateDeck, arg.Name, arg.DeckID, arg.PlayerID)
}

const upsertPlayerCard = `-- name: UpsertPlayerCard :exec
INSERT INTO player_cards (player_id, card_id, level, quantity) VALUES (?, ?, 1, 1)
ON DUPLICATE KEY UPDATE quantity = quantity + 1
`

type UpsertPlayerCardParams struct {
	PlayerID int64 `json:"player_id"`
	CardID   int32 `json:"card_id"`
}

func (q *Queries) UpsertPlayerCard(ctx context.Context, arg UpsertPlayerCardParams) error {
	_, err := q.db.ExecContext(ctx, upsertPlayerCard, arg.PlayerID, arg.CardID)
	return err
}
