// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: game_sessions.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const cancelGameSession = `-- name: CancelGameSession :exec
UPDATE game_sessions SET status = 'cancelled' WHERE session_id = ?
`

func (q *Queries) CancelGameSession(ctx context.Context, sessionID string) error {
	_, err := q.db.ExecContext(ctx, cancelGameSession, sessionID)
	return err
}

const completeGameSession = `-- name: CompleteGameSession :exec
UPDATE game_sessions
SET status = 'completed', ended_at = NOW(), winner_id = ?, player1_mmr_change = ?, player2_mmr_change = ?
WHERE session_id = ?
`

type CompleteGameSessionParams struct {
	WinnerID         *int64 `json:"winner_id"`
	Player1MmrChange *int32 `json:"player1_mmr_change"`
	Player2MmrChange *int32 `json:"player2_mmr_change"`
	SessionID        string `json:"session_id"`
}

func (q *Queries) CompleteGameSession(ctx context.Context, arg CompleteGameSessionParams) error {
	_, err := q.db.ExecContext(ctx, completeGameSession,
		arg.WinnerID,
		arg.Player1MmrChange,
		arg.Player2MmrChange,
		arg.SessionID,
	)
	return err
}

const createGameSession = `-- name: CreateGameSession :exec
INSERT INTO game_sessions (session_id, player1_id, player2_id, status, created_at, match_expires_at)
VALUES (?, ?, ?, 'waiting', NOW(), ?)
`

type CreateGameSessionParams struct {
	SessionID      string     `json:"session_id"`
	Player1ID      int64      `json:"player1_id"`
	Player2ID      int64      `json:"player2_id"`
	MatchExpiresAt *time.Time `json:"match_expires_at"`
}

func (q *Queries) CreateGameSession(ctx context.Context, arg CreateGameSessionParams) error {
	_, err := q.db.ExecContext(ctx, createGameSession,
		arg.SessionID,
		arg.Player1ID,
		arg.Player2ID,
		arg.MatchExpiresAt,
	)
	return err
}

const getExpiredWaitingSessions = `-- name: GetExpiredWaitingSessions :many
SELECT gs.session_id, gs.player1_id, gs.player2_id,
       u1.username, u2.username, u1.mmr, u2.mmr
FROM game_sessions gs
JOIN users u1 ON gs.player1_id = u1.id
JOIN users u2 ON gs.player2_id = u2.id
WHERE gs.status = 'waiting'
  AND gs.match_expires_at IS NOT NULL
  AND gs.match_expires_at < NOW()
`

type GetExpiredWaitingSessionsRow struct {
	SessionID  string `json:"session_id"`
	Player1ID  int64  `json:"player1_id"`
	Player2ID  int64  `json:"player2_id"`
	Username   string `json:"username"`
	Username_2 string `json:"username_2"`
	Mmr        int32  `json:"mmr"`
	Mmr_2      int32  `json:"mmr_2"`
}

func (q *Queries) GetExpiredWaitingSessions(ctx context.Context) ([]GetExpiredWaitingSessionsRow, error) {
	rows, err := q.db.QueryContext(ctx, getExpiredWaitingSessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetExpiredWaitingSessionsRow{}
	for rows.Next() {
		var i GetExpiredWaitingSessionsRow
		if err := rows.Scan(
			&i.SessionID,
			&i.Player1ID,
			&i.Player2ID,
			&i.Username,
			&i.Username_2,
			&i.Mmr,
			&i.Mmr_2,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSessionForAccept = `-- name: GetSessionForAccept :one
SELECT player1_id, player2_id, player1_ready, player2_ready, status
FROM game_sessions WHERE session_id = ?
`

type GetSessionForAcceptRow struct {
	Player1ID    int64              `json:"player1_id"`
	Player2ID    int64              `json:"player2_id"`
	Player1Ready *bool              `json:"player1_ready"`
	Player2Ready *bool              `json:"player2_ready"`
	Status       GameSessionsStatus `json:"status"`
}

func (q *Queries) GetSessionForAccept(ctx context.Context, sessionID string) (GetSessionForAcceptRow, error) {
	row := q.db.QueryRowContext(ctx, getSessionForAccept, sessionID)
	var i GetSessionForAcceptRow
	err := row.Scan(
		&i.Player1ID,
		&i.Player2ID,
		&i.Player1Ready,
		&i.Player2Ready,
		&i.Status,
	)
	return i, err
}

const getSessionForEndGame = `-- name: GetSessionForEndGame :one
SELECT gs.player1_id, gs.player2_id, u1.mmr, u2.mmr
FROM game_sessions gs
JOIN users u1 ON gs.player1_id = u1.id
JOIN users u2 ON gs.player2_id = u2.id
WHERE gs.session_id = ? AND gs.status = 'in_progress'
`

type GetSessionForEndGameRow struct {
	Player1ID int64 `json:"player1_id"`
	Player2ID int64 `json:"player2_id"`
	Mmr       int32 `json:"mmr"`
	Mmr_2     int32 `json:"mmr_2"`
}

func (q *Queries) GetSessionForEndGame(ctx context.Context, sessionID string) (GetSessionForEndGameRow, error) {
	row := q.db.QueryRowContext(ctx, getSessionForEndGame, sessionID)
	var i GetSessionForEndGameRow
	err := row.Scan(
		&i.Player1ID,
		&i.Player2ID,
		&i.Mmr,
		&i.Mmr_2,
	)
	return i, err
}

const getSessionStatus = `-- name: GetSessionStatus :one
SELECT player1_id, player2_id, status, winner_id, started_at, ended_at, player1_mmr_change, player2_mmr_change
FROM game_sessions WHERE session_id = ?
`

type GetSessionStatusRow struct {
	Player1ID        int64              `json:"player1_id"`
	Player2ID        int64              `json:"player2_id"`
	Status           GameSessionsStatus `json:"status"`
	WinnerID         *int64             `json:"winner_id"`
	StartedAt        *time.Time         `json:"started_at"`
	EndedAt          *time.Time         `json:"ended_at"`
	Player1MmrChange *int32             `json:"player1_mmr_change"`
	Player2MmrChange *int32             `json:"player2_mmr_change"`
}

func (q *Queries) GetSessionStatus(ctx context.Context, sessionID string) (GetSessionStatusRow, error) {
	row := q.db.QueryRowContext(ctx, getSessionStatus, sessionID)
	var i GetSessionStatusRow
	err := row.Scan(
		&i.Player1ID,
		&i.Player2ID,
		&i.Status,
		&i.WinnerID,
		&i.StartedAt,
		&i.EndedAt,
		&i.Player1MmrChange,
		&i.Player2MmrChange,
	)
	return i, err
}

const getSessionWithPlayers = `-- name: GetSessionWithPlayers :one
SELECT gs.player1_id, gs.player2_id, u1.username, u2.username, u1.mmr, u2.mmr, gs.status
FROM game_sessions gs
JOIN users u1 ON gs.player1_id = u1.id
JOIN users u2 ON gs.player2_id = u2.id
WHERE gs.session_id = ?
`

type GetSessionWithPlayersRow struct {
	Player1ID  int64              `json:"player1_id"`
	Player2ID  int64              `json:"player2_id"`
	Username   string             `json:"username"`
	Username_2 string             `json:"username_2"`
	Mmr        int32              `json:"mmr"`
	Mmr_2      int32              `json:"mmr_2"`
	Status     GameSessionsStatus `json:"status"`
}

func (q *Queries) GetSessionWithPlayers(ctx context.Context, sessionID string) (GetSessionWithPlayersRow, error) {
	row := q.db.QueryRowContext(ctx, getSessionWithPlayers, sessionID)
	var i GetSessionWithPlayersRow
	err := row.Scan(
		&i.Player1ID,
		&i.Player2ID,
		&i.Username,
		&i.Username_2,
		&i.Mmr,
		&i.Mmr_2,
		&i.Status,
	)
	return i, err
}

const setPlayer1Ready = `-- name: SetPlayer1Ready :execresult
UPDATE game_sessions SET player1_ready = TRUE
WHERE session_id = ? AND status = 'waiting'
`

func (q *Queries) SetPlayer1Ready(ctx context.Context, sessionID string) (sql.Result, error) {
	return q.db.ExecContext(ctx, setPlayer1Ready, sessionID)
}

const setPlayer2Ready = `-- name: SetPlayer2Ready :execresult
UPDATE game_sessions SET player2_ready = TRUE
WHERE session_id = ? AND status = 'waiting'
`

func (q *Queries) SetPlayer2Ready(ctx context.Context, sessionID string) (sql.Result, error) {
	return q.db.ExecContext(ctx, setPlayer2Ready, sessionID)
}

const startGameSession = `-- name: StartGameSession :execresult
UPDATE game_sessions
SET player1_ready = ?, player2_ready = ?, status = 'in_progress', started_at = NOW(), match_expires_at = NULL
WHERE session_id = ? AND status = 'waiting'
`

type StartGameSessionParams struct {
	Player1Ready *bool  `json:"player1_ready"`
	Player2Ready *bool  `json:"player2_ready"`
	SessionID    string `json:"session_id"`
}

func (q *Queries) StartGameSession(ctx context.Context, arg StartGameSessionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, startGameSession, arg.Player1Ready, arg.Player2Ready, arg.SessionID)
}

const updateUserMMR = `-- name: UpdateUserMMR :exec
UPDATE users SET mmr = mmr + ? WHERE id = ?
`

type UpdateUserMMRParams struct {
	Mmr int32 `json:"mmr"`
	ID  int64 `json:"id"`
}

func (q *Queries) UpdateUserMMR(ctx context.Context, arg UpdateUserMMRParams) error {
	_, err := q.db.ExecContext(ctx, updateUserMMR, arg.Mmr, arg.ID)
	return err
}
