// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: gameplay.sql

package db

import (
	"context"
)

const getGameSessionPlayers = `-- name: GetGameSessionPlayers :one
SELECT gs.player1_id, gs.player2_id, u1.username, u2.username
FROM game_sessions gs
JOIN users u1 ON gs.player1_id = u1.id
JOIN users u2 ON gs.player2_id = u2.id
WHERE gs.session_id = ? AND gs.status = 'in_progress'
`

type GetGameSessionPlayersRow struct {
	Player1ID  int64  `json:"player1_id"`
	Player2ID  int64  `json:"player2_id"`
	Username   string `json:"username"`
	Username_2 string `json:"username_2"`
}

func (q *Queries) GetGameSessionPlayers(ctx context.Context, sessionID string) (GetGameSessionPlayersRow, error) {
	row := q.db.QueryRowContext(ctx, getGameSessionPlayers, sessionID)
	var i GetGameSessionPlayersRow
	err := row.Scan(
		&i.Player1ID,
		&i.Player2ID,
		&i.Username,
		&i.Username_2,
	)
	return i, err
}
