// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: matchmaking_queue.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const deleteFromQueue = `-- name: DeleteFromQueue :execresult
DELETE FROM matchmaking_queue WHERE user_id = ?
`

func (q *Queries) DeleteFromQueue(ctx context.Context, userID int64) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteFromQueue, userID)
}

const deleteFromQueueByUsers = `-- name: DeleteFromQueueByUsers :exec
DELETE FROM matchmaking_queue WHERE user_id IN (?, ?)
`

type DeleteFromQueueByUsersParams struct {
	UserID   int64 `json:"user_id"`
	UserID_2 int64 `json:"user_id_2"`
}

func (q *Queries) DeleteFromQueueByUsers(ctx context.Context, arg DeleteFromQueueByUsersParams) error {
	_, err := q.db.ExecContext(ctx, deleteFromQueueByUsers, arg.UserID, arg.UserID_2)
	return err
}

const getActiveQueue = `-- name: GetActiveQueue :many
SELECT q.user_id, u.username, q.mmr, q.joined_at
FROM matchmaking_queue q
JOIN users u ON q.user_id = u.id
WHERE u.is_banned = FALSE
ORDER BY q.joined_at ASC
`

type GetActiveQueueRow struct {
	UserID   int64     `json:"user_id"`
	Username string    `json:"username"`
	Mmr      int32     `json:"mmr"`
	JoinedAt time.Time `json:"joined_at"`
}

func (q *Queries) GetActiveQueue(ctx context.Context) ([]GetActiveQueueRow, error) {
	rows, err := q.db.QueryContext(ctx, getActiveQueue)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetActiveQueueRow{}
	for rows.Next() {
		var i GetActiveQueueRow
		if err := rows.Scan(
			&i.UserID,
			&i.Username,
			&i.Mmr,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOngoingGameSession = `-- name: GetOngoingGameSession :one
SELECT session_id FROM game_sessions
WHERE (player1_id = ? OR player2_id = ?) AND status IN ('waiting', 'in_progress')
`

type GetOngoingGameSessionParams struct {
	Player1ID int64 `json:"player1_id"`
	Player2ID int64 `json:"player2_id"`
}

func (q *Queries) GetOngoingGameSession(ctx context.Context, arg GetOngoingGameSessionParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getOngoingGameSession, arg.Player1ID, arg.Player2ID)
	var session_id string
	err := row.Scan(&session_id)
	return session_id, err
}

const getQueueEntryByUserID = `-- name: GetQueueEntryByUserID :one
SELECT id FROM matchmaking_queue WHERE user_id = ?
`

func (q *Queries) GetQueueEntryByUserID(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, getQueueEntryByUserID, userID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getQueueStatus = `-- name: GetQueueStatus :one
SELECT mmr, joined_at FROM matchmaking_queue WHERE user_id = ?
`

type GetQueueStatusRow struct {
	Mmr      int32     `json:"mmr"`
	JoinedAt time.Time `json:"joined_at"`
}

func (q *Queries) GetQueueStatus(ctx context.Context, userID int64) (GetQueueStatusRow, error) {
	row := q.db.QueryRowContext(ctx, getQueueStatus, userID)
	var i GetQueueStatusRow
	err := row.Scan(&i.Mmr, &i.JoinedAt)
	return i, err
}

const getUserForMatchmaking = `-- name: GetUserForMatchmaking :one
SELECT username, mmr, is_banned FROM users WHERE id = ?
`

type GetUserForMatchmakingRow struct {
	Username string `json:"username"`
	Mmr      int32  `json:"mmr"`
	IsBanned bool   `json:"is_banned"`
}

func (q *Queries) GetUserForMatchmaking(ctx context.Context, id int64) (GetUserForMatchmakingRow, error) {
	row := q.db.QueryRowContext(ctx, getUserForMatchmaking, id)
	var i GetUserForMatchmakingRow
	err := row.Scan(&i.Username, &i.Mmr, &i.IsBanned)
	return i, err
}

const insertIntoQueue = `-- name: InsertIntoQueue :exec
INSERT INTO matchmaking_queue (user_id, mmr) VALUES (?, ?)
`

type InsertIntoQueueParams struct {
	UserID int64 `json:"user_id"`
	Mmr    int32 `json:"mmr"`
}

func (q *Queries) InsertIntoQueue(ctx context.Context, arg InsertIntoQueueParams) error {
	_, err := q.db.ExecContext(ctx, insertIntoQueue, arg.UserID, arg.Mmr)
	return err
}

const requeuePlayer = `-- name: RequeuePlayer :exec
INSERT INTO matchmaking_queue (user_id, mmr, joined_at) VALUES (?, ?, NOW())
ON DUPLICATE KEY UPDATE joined_at = NOW()
`

type RequeuePlayerParams struct {
	UserID int64 `json:"user_id"`
	Mmr    int32 `json:"mmr"`
}

func (q *Queries) RequeuePlayer(ctx context.Context, arg RequeuePlayerParams) error {
	_, err := q.db.ExecContext(ctx, requeuePlayer, arg.UserID, arg.Mmr)
	return err
}
