package effects

import (
	"encoding/json"
	"math/rand"
)

// CardDefinition is the immutable template loaded from the DB at startup.
type CardDefinition struct {
	CardID    int
	Name      string
	Colour    string
	Rarity    string
	Cost      int
	BaseAtk   int
	BaseHP    int
	Abilities []AbilityDefinition
}

// AbilityDefinition maps 1:1 to a card_abilities row.
type AbilityDefinition struct {
	TriggerType string          `json:"trigger_type"`
	EffectType  string          `json:"effect_type"`
	Params      json.RawMessage `json:"params"`
}

// CardInstance is a live card on the board with mutable state.
type CardInstance struct {
	InstanceID           int
	Definition           *CardDefinition
	CurrentAtk           int
	CurrentHP            int
	MaxHP                int
	ChargeTicksRemaining int
	ChargeTicksTotal     int
	IsCharging           bool
	DamageReduction      int // set by shield effect, applied before damage
	Abilities            []Ability
}

// BoardPosition identifies a cell on the board.
type BoardPosition struct {
	Row int
	Col int
}

// EffectEvent represents an event generated by an effect for the combat log.
type EffectEvent struct {
	Type           string
	SourcePlayerID int64
	SourceCardID   int
	SourceRow      int
	SourceCol      int
	TargetCardID   int
	TargetRow      int
	TargetCol      int
	TargetIsLeader bool
	Value          int
	ValueHP        int
	CardName       string
	Message        string
}

// TargetOverride is returned by TargetModifier abilities to change attack targeting.
type TargetOverride struct {
	TargetCard     *CardInstance
	TargetRow      int
	TargetCol      int
	TargetIsLeader bool
	TargetPlayerID int64
}

// EffectContext provides everything an ability needs to read/mutate game state.
type EffectContext struct {
	Source    *CardInstance
	Target   *CardInstance // set for on_damaged/reflect: the attacker
	SourcePos BoardPosition

	// Which player owns the source card
	SourcePlayerID int64
	IsPlayer1      bool

	// Board state (pointers so effects can mutate)
	Board1 *[2][3]*CardInstance // Player 1's board
	Board2 *[2][3]*CardInstance // Player 2's board

	// Leader health (pointers for mutation)
	Player1HP *int
	Player2HP *int

	// Leader attack values
	Player1LeaderAtk int
	Player2LeaderAtk int

	// Elixir caps (pointers for mutation by elixir_overflow)
	Player1ElixirCap *int
	Player2ElixirCap *int

	// Callbacks
	ReturnToHand func(playerID int64, def *CardDefinition)
	CardStore    *CardDefinitionStore

	// Hand info for colour-counting (Travelling Merchant)
	SourcePlayerDeckColours []string

	// Deterministic RNG
	RNG *rand.Rand
}

// GetOwnBoard returns the board belonging to the source card's owner.
func (ctx *EffectContext) GetOwnBoard() *[2][3]*CardInstance {
	if ctx.IsPlayer1 {
		return ctx.Board1
	}
	return ctx.Board2
}

// GetOpponentBoard returns the opponent's board.
func (ctx *EffectContext) GetOpponentBoard() *[2][3]*CardInstance {
	if ctx.IsPlayer1 {
		return ctx.Board2
	}
	return ctx.Board1
}

// GetOwnHP returns a pointer to the source player's HP.
func (ctx *EffectContext) GetOwnHP() *int {
	if ctx.IsPlayer1 {
		return ctx.Player1HP
	}
	return ctx.Player2HP
}

// GetOpponentHP returns a pointer to the opponent's HP.
func (ctx *EffectContext) GetOpponentHP() *int {
	if ctx.IsPlayer1 {
		return ctx.Player2HP
	}
	return ctx.Player1HP
}

// GetOpponentPlayerID returns the opponent's player ID.
func (ctx *EffectContext) GetOpponentPlayerID() int64 {
	// We don't store opponent player ID directly; the caller should set this
	// For now, return 0 as a sentinel
	return 0
}

// GetOwnElixirCap returns a pointer to the source player's elixir cap.
func (ctx *EffectContext) GetOwnElixirCap() *int {
	if ctx.IsPlayer1 {
		return ctx.Player1ElixirCap
	}
	return ctx.Player2ElixirCap
}
